# Change these first
owner: Intus-AS # Your GitHub organization or username, where this repository lives
repo: Types-status # The name of this repository

sites:
  - name: mardahl.no
    url: https://mardahl.no
  - name: verksted.mardahl.no
    url: https://verksted.mardahl.no
  - name: industri.mardahl.no
    url: https://industri.mardahl.no
  - name: frumento.no
    url: https://frumento.no
  - name: osteriamoderna.no
    url: https://osteriamoderna.no
  - name: frostabrygge.no
    url: https://frostabrygge.no
  - name: yggdrasilmiljo.no
    url: https://yggdrasilmiljo.no
  - name: simonsinterior.no
    url: https://simonsinterior.no
  - name: leospizza.no
    url: https://leospizza.no
  - name: xstadion.no
    url: https://xstadion.no
  - name: dininfoskjerm.no
    url: https://dininfoskjerm.no
  - name: alpha-as.no
    url: https://alpha-as.no
  - name: biztek.no
    url: https://biztek.no
  - name: lakksalg.no
    url: https://lakksalg.no
  - name: ilfornaio.no
    url: https://ilfornaio.no
  - name: crispyfriedchicken.no
    url: https://crispyfriedchicken.no
  - name: cfcdrive.no
    url: https://cfcdrive.no
  - name: nordingpartners.no
    url: https://nordingpartners.no
  - name: lokalskjermen.no
    url: https://lokalskjermen.no
  - name: voldautospa.no
    url: https://voldautospa.no
  - name: types.no
    url: https://types.no
  - name: uniloq.io
    url: https://uniloq.io
  - name: hotell-skolestua.no
    url: https://hotell-skolestua.no
  - name: meetly.no
    url: https://meetly.no
  - name: vikenmidtre.no
    url: https://vikenmidtre.no
  - name: ck.no
    url: https://ck.no
  - name: trv-gruppen.ck.no
    url: https://trv-gruppen.ck.no
  - name: mederi.no
    url: https://mederi.no
  - name: loginfinans.no
    url: https://loginfinans.no
  - name: smålandbåtforening.no
    url: https://smålandbåtforening.no
  - name: frent.no
    url: https://frent.no
  - name: tilveksten.no
    url: https://tilveksten.no
  - name: stem.hegrasparebank.no
    url: https://stem.hegrasparebank.no
  - name: all-rf.no
    url: https://all-rf.no
  - name: mus.as
    url: https://mus.as
  - name: all-ror.no
    url: https://all-ror.no
  - name: hojemgard.no
    url: https://hojemgard.no
  - name: mariaskjokken.no
    url: https://mariaskjokken.no
  - name: intus.no
    url: https://intus.no
  - name: roskaft.no
    url: https://roskaft.no
  - name: operadisetra.no
    url: https://operadisetra.no
  - name: ppmprosjekt.no
    url: https://ppmprosjekt.no
  - name: fossli.no
    url: https://fossli.no
  - name: helgeposen.no
    url: https://helgeposen.no
  - name: djupvika.no
    url: https://djupvika.no
  - name: smakenavspania.no
    url: https://smakenavspania.no
  - name: krradgivning.no
    url: https://krradgivning.no
  - name: turbuss1.no
    url: https://turbuss1.no
  - name: utpaasjoen.no
    url: https://utpaasjoen.no
  - name: frostafrisor.no
    url: https://frostafrisor.no
  - name: hell-catering.no
    url: https://hell-catering.no
  - name: tobbdrift.no
    url: https://tobbdrift.no
  - name: klostergardentautra.no
    url: https://klostergardentautra.no
  - name: venklinikken.no
    url: https://venklinikken.no
  - name: frisk-salat.no
    url: https://frisk-salat.no
  - name: portalenagdenes.no
    url: https://portalenagdenes.no
  - name: xfitness.no
    url: https://xfitness.no
  - name: eidum.no
    url: https://eidum.no
  - name: frostabua.no
    url: https://frostabua.no
  - name: easyfit.no
    url: https://easyfit.no
  - name: frostavvs.no
    url: https://frostavvs.no
  - name: grano.no
    url: https://grano.no
  - name: fallskjerm.no
    url: https://fallskjerm.no
  - name: vingemaskin.no
    url: https://vingemaskin.no
  - name: publy.no
    url: https://publy.no
  - name: app.publy.no
    url: https://app.publy.no
  - name: partner.publy.no
    url: https://partner.publy.no
  - name: hammerplanteskole.no
    url: https://hammerplanteskole.no
  - name: hospitalet.no
    url: https://hospitalet.no
  - name: stenets.no
    url: https://stenets.no
  - name: orsand.no
    url: https://orsand.no
  - name: minilagertrondheim.no
    url: https://minilagertrondheim.no
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /Types-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
