# Change these first
owner: Intus-AS # Your GitHub organization or username, where this repository lives
repo: Types-status # The name of this repository

sites:
  - name: mardahl.no
    url: https://mardahl.no
  - name: frumento.no
    url: https://frumento.no
  - name: osteriamoderna.no
    url: https://osteriamoderna.no
  - name: frostabrygge.no
    url: https://frostabrygge.no
  - name: yggdrasilmiljo.no
    url: https://yggdrasilmiljo.no
  - name: simonsinterior.no
    url: https://simonsinterior.no
  - name: leospizza.no
    url: https://leospizza.no
  - name: xstadion.no
    url: https://xstadion.no
  - name: dininfoskjerm.no
    url: https://dininfoskjerm.no
  - name: alpha-as.no
    url: https://alpha-as.no
  - name: biztek.no
    url: https://biztek.no
  - name: lakksalg.no
    url: https://lakksalg.no
  - name: ilfornaio.no
    url: https://ilfornaio.no
  - name: crispyfriedchicken.no
    url: https://crispyfriedchicken.no
  - name: cfcdrive.no
    url: https://cfcdrive.no
  - name: nordingpartners.no
    url: https://nordingpartners.no
  - name: lokalskjermen.no
    url: https://lokalskjermen.no
  - name: voldautospa.no
    url: https://voldautospa.no
  - name: types.no
    url: https://types.no
  - name: uniloq.io
    url: https://uniloq.io
  - name: hotell-skolestua.no
    url: https://hotell-skolestua.no
  - name: meetly.no
    url: https://meetly.no
  - name: bonderuta.no
    url: https://bonderuta.no
  - name: vikenmidtre.no
    url: https://vikenmidtre.no
  - name: ck.no
    url: https://ck.no


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /Types-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
